version: '3'

services:
  postgresql:
    image: postgres
    container_name: users
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=postgres
    command: postgres
    restart: always
